export const indianBanks = [
  "State Bank of India (SBI)",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "Punjab National Bank (PNB)",
  "Bank of Baroda",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India",
  "IndusInd Bank",
  "Yes Bank",
  "IDFC First Bank",
  "Federal Bank",
  "IDBI Bank",
  "Bandhan Bank",
  "RBL Bank",
  "South Indian Bank",
  "Karur Vysya Bank",
  "City Union Bank",
  "Tamilnad Mercantile Bank",
  "Jammu & Kashmir Bank",
  "Karnataka Bank",
  "DCB Bank",
  "Nainital Bank",
  "Dhanlaxmi Bank",
  "Saraswat Bank",
  "Cosmos Bank",
  "Shamrao Vithal Co-operative Bank",
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Utkarsh Small Finance Bank",
  "Suryoday Small Finance Bank",
  "ESAF Small Finance Bank",
  "Fino Payments Bank",
  "Airtel Payments Bank",
  "India Post Payments Bank (IPPB)",
  "Paytm Payments Bank",
  "Jio Payments Bank",
  "NSDL Payments Bank",
  "Central Bank of India",
  "Indian Bank",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
];

export const internationalBanks = [
  "JPMorgan Chase",
  "Bank of America",
  "Citibank",
  "Wells Fargo",
  "Goldman Sachs",
  "Morgan Stanley",
  "HSBC",
  "Standard Chartered",
  "Barclays",
  "Lloyds Banking Group",
  "NatWest Group",
  "Santander",
  "BNP Paribas",
  "Crédit Agricole",
  "Société Générale",
  "Deutsche Bank",
  "Commerzbank",
  "UBS",
  "ING Group",
  "Rabobank",
  "ABN AMRO",
  "BBVA",
  "UniCredit",
  "Intesa Sanpaolo",
  "Royal Bank of Canada (RBC)",
  "TD Bank",
  "Bank of Montreal (BMO)",
  "Scotiabank",
  "CIBC",
  "Commonwealth Bank (Australia)",
  "Westpac",
  "ANZ Bank",
  "National Australia Bank (NAB)",
  "Macquarie Bank",
  "Mizuho Bank",
  "MUFG Bank",
  "Sumitomo Mitsui Banking Corporation (SMBC)",
  "Japan Post Bank",
  "DBS Bank",
  "OCBC Bank",
  "United Overseas Bank (UOB)",
  "Maybank",
  "CIMB Bank",
  "Public Bank",
  "RHB Bank",
  "AmBank",
  "Bangkok Bank",
  "Kasikornbank",
  "Siam Commercial Bank (SCB)",
  "Krungthai Bank",
  "Emirates NBD",
  "First Abu Dhabi Bank (FAB)",
  "Qatar National Bank (QNB)",
  "Mashreq Bank",
  "National Bank of Kuwait",
  "Saudi National Bank (SNB)",
  "Al Rajhi Bank",
  "Riyad Bank",
  "Arab Bank",
  "Standard Bank (South Africa)",
  "FirstRand Bank",
  "Absa Bank",
  "Nedbank",
  "Itaú Unibanco",
  "Banco Bradesco",
  "Banco do Brasil",
  "Bancolombia",
  "Banco de Chile",
];

export const bankGroups = [
  { heading: "Indian banks", items: indianBanks.map((b) => ({ label: b, value: b })) },
  { heading: "International banks", items: internationalBanks.map((b) => ({ label: b, value: b })) },
];

export const currencyOptions = [
  { label: "INR — Indian Rupee", value: "INR" },
  { label: "USD — US Dollar", value: "USD" },
  { label: "EUR — Euro", value: "EUR" },
  { label: "GBP — British Pound", value: "GBP" },
  { label: "JPY — Japanese Yen", value: "JPY" },
  { label: "CNY — Chinese Yuan", value: "CNY" },
  { label: "AUD — Australian Dollar", value: "AUD" },
  { label: "CAD — Canadian Dollar", value: "CAD" },
  { label: "CHF — Swiss Franc", value: "CHF" },
  { label: "SGD — Singapore Dollar", value: "SGD" },
  { label: "HKD — Hong Kong Dollar", value: "HKD" },
  { label: "NZD — New Zealand Dollar", value: "NZD" },
  { label: "SEK — Swedish Krona", value: "SEK" },
  { label: "NOK — Norwegian Krone", value: "NOK" },
  { label: "DKK — Danish Krone", value: "DKK" },
  { label: "AED — UAE Dirham", value: "AED" },
  { label: "SAR — Saudi Riyal", value: "SAR" },
  { label: "QAR — Qatari Riyal", value: "QAR" },
  { label: "KWD — Kuwaiti Dinar", value: "KWD" },
  { label: "BHD — Bahraini Dinar", value: "BHD" },
  { label: "OMR — Omani Rial", value: "OMR" },
  { label: "JOD — Jordanian Dinar", value: "JOD" },
  { label: "MYR — Malaysian Ringgit", value: "MYR" },
  { label: "THB — Thai Baht", value: "THB" },
  { label: "IDR — Indonesian Rupiah", value: "IDR" },
  { label: "PHP — Philippine Peso", value: "PHP" },
  { label: "VND — Vietnamese Dong", value: "VND" },
  { label: "KRW — South Korean Won", value: "KRW" },
  { label: "ZAR — South African Rand", value: "ZAR" },
  { label: "BRL — Brazilian Real", value: "BRL" },
  { label: "MXN — Mexican Peso", value: "MXN" },
  { label: "RUB — Russian Ruble", value: "RUB" },
  { label: "TRY — Turkish Lira", value: "TRY" },
  { label: "PLN — Polish Zloty", value: "PLN" },
  { label: "ILS — Israeli Shekel", value: "ILS" },
  { label: "NGN — Nigerian Naira", value: "NGN" },
  { label: "EGP — Egyptian Pound", value: "EGP" },
  { label: "PKR — Pakistani Rupee", value: "PKR" },
  { label: "BDT — Bangladeshi Taka", value: "BDT" },
  { label: "LKR — Sri Lankan Rupee", value: "LKR" },
  { label: "NPR — Nepalese Rupee", value: "NPR" },
];

export function currencyLabel(code) {
  const c = currencyOptions.find((o) => o.value === code);
  return c ? c.label : code;
}